name: Build SPD Dump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
        config: [Release, CustDebug]
    steps:
      - name: Setup MSVS
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Windows SSH Key workarounds
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          cat << EOF > $HOME/.ssh/known_hosts
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          EOF

      - name: Build SPD Dump (${{ matrix.arch }} - ${{ matrix.config }})
        run: |
          git clone git@github.com:TomKing062/spd_dump_it.git
          cd spd_dump_it
          echo "GIT_SHA1=$((git rev-parse HEAD).Substring(0, 7))" >> "$GITHUB_ENV"
          New-Item -ItemType Directory -Force -Path ./build/${{ matrix.arch }}/${{ matrix.config }}/
          msbuild spd_dump.vcxproj /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.arch == 'x64' && 'x64' || 'win32' }} /p:OutDir=./build/${{ matrix.arch }}/${{ matrix.config }}/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spd_dump_it_${{ env.GIT_SHA1 }}_${{ matrix.arch }}_${{ matrix.config }}
          path: ./spd_dump_it/build/${{ matrix.arch }}/${{ matrix.config }}/
